### ISSUE TITLE
Traducción al catalán

### ISSUE THREAD

**Issue by amirabet** [carlosescri/nt-cookies#1]
Buenas Carlos.
Me ha parecido un muy buen plugin que incluso se podría combinar con una serie de opciones para poder crear parte del texto de Condiciones Legales de un Word Press (especialmente en lo que a tipos de Cookies utilizadas se refiere).
Aunque por el momento la aportación rápida y humilde que puedo hacer es la de traducirlo al catalán.

Un saludo.

**Comment by carlosescri** [comment]
Gracias Artur. El plugin no es perfecto ni mucho menos, y todavía tiene margen de mejora (el mensaje vuelve a aparecer si se borra la cookie que pone en el navegador).

Si quieres aportar la traducción al catalán puedo buscar un hueco e integrarla, pero no sé cuándo ya que este plugin era a modo de ejemplo sobre cómo se hacen plugins para WordPress. De hecho mis blogs ya no están en WordPress, sino en [Jekyll](http://jekyllrb.com) que es más rápido, seguro y, para lo que yo hago, más que suficiente. Por eso no voy a seguir muy metido en esto de los plugins, pero si me envías lo que consideres que haya que traducir, como te digo, intento añadirlo.

Gracias por tus comentarios. Cierro el ticket de momento, si quieres seguimos la conversación en el [post del blog](http://nettoys.es/2014/politica-de-cookies-plugin-para-wordpress), que es lo suyo.

Un saludo.

C.
